In [2]:
#import necessary libraries
import pandas as pd
import numpy as np

In [8]:
#import the provided dataset into motebook
from google.colab import files
uploaded = files.upload()

Saving FoodBalanceSheets.csv to FoodBalanceSheets (1).csv

In [10]:
#convert dataset into dataframe
df = pd.read_csv("FoodBalanceSheets (1).csv", encoding = "latin-1")

In [12]:
#view data
df.head(10)

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
5,4,Algeria,2903,Vegetal Products,664,Food supply (kcal/capita/day),kcal/capita/day,2932.00,2958.00,2941.00,2921.00,2932.00
6,4,Algeria,2903,Vegetal Products,674,Protein supply quantity (g/capita/day),g/capita/day,67.14,67.38,67.37,66.11,67.10
7,4,Algeria,2903,Vegetal Products,684,Fat supply quantity (g/capita/day),g/capita/day,53.84,54.72,52.04,55.59,54.57
8,4,Algeria,2941,Animal Products,664,Food supply (kcal/capita/day),kcal/capita/day,444.00,421.00,431.00,421.00,390.00
9,4,Algeria,2941,Animal Products,674,Protein supply quantity (g/capita/day),g/capita/day,27.76,26.97,27.35,26.71,24.73
10,4,Algeria,2941,Animal Products,684,Fat supply quantity (g/capita/day),g/capita/day,26.22,24.64,25.37,24.60,22.71
11,4,Algeria,2905,Cereals - Excluding Beer,5511,Production,1000 tonnes,3436.00,3761.00,3445.00,3478.00,6065.00
12,4,Algeria,2905,Cereals - Excluding Beer,5611,Import Quantity,1000 tonnes,12604.00,13983.00,13523.00,13039.00,13182.00
13,4,Algeria,2905,Cereals - Excluding Beer,5072,Stock Variation,1000 tonnes,684.00,1663.00,905.00,705.00,2226.00
14,4,Algeria,2905,Cereals - Excluding Beer,5911,Export Quantity,1000 tonnes,3.00,7.00,7.00,10.00,17.00
15,4,Algeria,2905,Cereals - Excluding Beer,5301,Domestic supply quantity,1000 tonnes,15353.00,16075.00,16056.00,15803.00,17004.00
16,4,Algeria,2905,Cereals - Excluding Beer,5521,Feed,1000 tonnes,4725.00,5070.00,4838.00,4667.00,5266.00
17,4,Algeria,2905,Cereals - Excluding Beer,5527,Seed,1000 tonnes,177.00,189.00,197.00,202.00,278.00
18,4,Algeria,2905,Cereals - Excluding Beer,5123,Losses,1000 tonnes,1084.00,1203.00,1148.00,1121.00,1253.00
19,4,Algeria,2905,Cereals - Excluding Beer,5131,Processing,1000 tonnes,35.00,38.00,37.00,33.00,44.00

In [16]:
df['Y2014']. isnull()

0        False
1        False
2        False
3        False
4        False
         ...
60938    False
60939    False
60940    False
60941    False
60942    False
Name: Y2014, Length: 60943, dtype: bool

In [17]:
#the total number of missing data in 2014
total_missing_data = df['Y2014'].isnull().sum()
print("Total number of missing data in 'Y2014':", total_missing_data)

Total number of missing data in 'Y2014': 1589

In [18]:
#Select columns ‘Y2017’ and ‘Area’
result = df[['Y2017', 'Area']]

#Perform a groupby operation on ‘Area’
result = df[['Y2017', 'Area']].groupby('Area').sum()

#Areas with the highest sum in 2017
area_highest_sum = result.idxmax()[0]
highest_sum = result.max()[0]

print("Area with the highest sum in 2017:", area_highest_sum)
print("Highest sum in 2017:", highest_sum)

Area with the highest sum in 2017: Nigeria
Highest sum in 2017: 1483268.23

In [34]:

#Select columns ‘Y2017’ and ‘Area’ and Perform a groupby operation on ‘Area’
result = df[['Y2017', 'Area']].groupby('Area').sum()

#Which of these Areas had the 7th lowest sum in 2017?
sorted = result.sort_values(by='Y2017')
area_with_7th_lowest_sum = sorted.index[6]

print("Area with the 7th lowest sum in 2017:", area_with_7th_lowest_sum)

sorted = sort_
area_7th_lowest_sum = result.idxmin()[0]

print("Area with the 7th lowest sum in 2017:", area_7th_lowest_sum)

Area with the 7th lowest sum in 2017: Guinea-Bissau

In [40]:


# Calculate the mean and standard deviation
mean_2017 = df['Y2017'].mean()
std_2017 = df['Y2017'].std()


# Round the mean and standard deviation to 2 decimal places
mean_2017 = round(mean_2017, 2)
std_2017 = round(std_2017, 2)

print("Mean of Y2017:", mean_2017)
print("std of Y2017:", std_2017)

Mean of Y2017: 140.92
std of Y2017: 1671.86

In [ ]:
# What is the total sum of Wine produced in 2015 and 2018 respectively?

wine_production = df[['Y2015', 'Y2018']].groupby('Item').sum()

In [48]:
#What is the total number of unique countries in the dataset?

total_countries = df['Area'].nunique()
print("Total number of unique countries:", total_countries)

Total number of unique countries: 49